
---

-   name: install_git
    when:
        -   is_regular_user_only | default(true) | bool == false
    dnf:
        name: git
        state: present
    become: yes

-   name: configure_git_for_primary_user
    template:
        src: gitconfig
        dest: ~/.gitconfig
        mode: 0644
    vars:
        set_author_git_config: True

-   name: configure_git_for_system
    when:
        -   is_regular_user_only | default(true) | bool == false
    template:
        src: gitconfig
        dest: /etc/gitconfig
        mode: 0644
        owner: root
        group: root
    become: yes
    vars:
        set_author_git_config: True

###############################################################################
# EOF
###############################################################################

