
---

-   name: install_git
    dnf:
        name: git
        state: present
    become: yes

-   name: configure_git_for_primary_user
    template:
        src: gitconfig
        dest: ~/.gitconfig
        mode: 0644
    vars:
        is_primary_user_git_config: True

-   name: configure_git_for_system
    template:
        src: gitconfig
        dest: /etc/gitconfig
        mode: 0644
        owner: root
        group: root
    become: yes
    vars:
        is_primary_user_git_config: True

###############################################################################
# EOF
###############################################################################

